FROM webdevops/php-nginx-dev:8.2-alpine

ARG ARCHITECTURE="linux/amd64"

RUN set -eux; \
  if [ "$ARCHITECTURE" = "linux/arm64" ]; then \
    wget -O "/usr/local/bin/go-replace" "https://github.com/webdevops/goreplace/releases/download/1.1.2/gr-arm64-linux" \
    && chmod +x "/usr/local/bin/go-replace" \
    && "/usr/local/bin/go-replace" --version; \
  fi

WORKDIR /app

COPY ./docker/nginx/server.conf /opt/docker/etc/nginx/conf.d/additional_configuration.conf

COPY ./ .

