<div class="block">
    <h3 class="section-title">
        <span>Labels</span>
        <svg class="tab-arrow" xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 24 24" fill="#6BC07F">
            <path d="M0 7.33l2.829-2.83 9.175 9.339 9.167-9.339 2.829 2.83-11.996 12.17z"></path>
        </svg>
    </h3>
    <a class="cmtt-documentation-link"
       href="https://creativeminds.helpscoutdocs.com/article/109-cmtg-getting-started-changing-labels"
       target="_blank">
        Documentation <span class="dashicons dashicons-external"></span>
    </a>
    <table class="floated-form-table form-table">
        <tr valign="top">
            <th scope="row">Glossary Item singular label</th>
            <td><input type="text" name="cmtt_glossaryItemSingularName" value="<?php echo \CM\CMTT_Settings::get('cmtt_glossaryItemSingularName', 'Glossary Item'); ?>" /></td>
            <td colspan="2" class="cmtt_field_help_container">
                The label describing the CM Tooltip Glossary Custom Post Types, often used to generate the breadcrumbs in themes. Default: "Glossary Item"
                <br/><i>This label is a part of the Permalink Structure. It's best to refresh the permalink structure database. (Go to Settings -> Permalinks -> "Save Changes")</i>
            </td>
        </tr>
        <tr valign="top">
            <th scope="row">Title attribute prefix</th>
            <td><input type="text" name="cmtt_titleAttributeLabelPrefix" value="<?php echo \CM\CMTT_Settings::get('cmtt_titleAttributeLabelPrefix', 'Glossary:'); ?>" /></td>
            <td colspan="2" class="cmtt_field_help_container">
                The text which appears in the title attribute if the option: "Show HTML "title" attribute for glossary links" is enabled.
            </td>
        </tr>
        <tr valign="top">
            <th scope="row">Sharing box label</th>
            <td><input type="text" name="cmtt_glossaryShowShareBoxLabel" value="<?php echo \CM\CMTT_Settings::get('cmtt_glossaryShowShareBoxLabel', 'Share This'); ?>" /></td>
            <td colspan="2" class="cmtt_field_help_container">
                What should be the label of the sharing box on the Glossary Index Page. Leave blank to disable. Default: "Share This"
                <br/><i>Works only if "Show Glossary Index page with definition" is enabled</i>
            </td>
        </tr>
        <tr valign="top">
            <th scope="row">Label of the search input on the Glossary Index page</th>
            <td><input type="text" name="cmtt_glossary_SearchLabel" value="<?php echo esc_attr(\CM\CMTT_Settings::get('cmtt_glossary_SearchLabel')); ?>" /></td>
            <td colspan="2" class="cmtt_field_help_container">This is the label for the search input appearing on the Glossary Index page.
                <br/><i>Works only if the "Show the search on the Glossary Index page" is enabled.</i></td>
        </tr>
        <tr valign="top">
            <th scope="row">Placeholder of the search input on the Glossary Index page</th>
            <td><input type="text" name="cmtt_glossary_SearchPlaceholder" value="<?php echo esc_attr(\CM\CMTT_Settings::get('cmtt_glossary_SearchPlaceholder')); ?>" /></td>
            <td colspan="2" class="cmtt_field_help_container">This is the placeholder for the search input appearing on the Glossary Index page.
                <br/><i>Works only if the "Show the search on the Glossary Index page" is enabled.</i></td>
        </tr>
        <tr valign="top">
            <th scope="row">Label of the search button on the Glossary Index page</th>
            <td><input type="text" name="cmtt_glossary_SearchButtonLabel" value="<?php echo esc_attr(\CM\CMTT_Settings::get('cmtt_glossary_SearchButtonLabel')); ?>" /></td>
            <td colspan="2" class="cmtt_field_help_container">This is the label for the search button appearing on the Glossary Index page.
                <br/><i>Works only if the "Show the search on the Glossary Index page" is enabled.</i></td>
        </tr>
        <tr valign="top">
            <th scope="row">Text for "Search Hint" on the Glossary Index page</th>
            <td><textarea name="cmtt_glossarySearchHelp"><?php echo esc_attr(\CM\CMTT_Settings::get('cmtt_glossarySearchHelp')); ?></textarea></td>
            <td colspan="2" class="cmtt_field_help_container">This is the text for the help on the Glossary Index page.
                <br/><i>Works only if the "Show the search on the Glossary Index page" is enabled.</i></td>
        </tr>
        <tr valign="top">
            <th scope="row">Text for "no results" on the Glossary Index page</th>
            <td><input type="text" name="cmtt_glossary_NoResultsLabel" value="<?php echo esc_attr(\CM\CMTT_Settings::get('cmtt_glossary_NoResultsLabel')); ?>" /></td>
            <td colspan="2" class="cmtt_field_help_container">This is the text which appears if the filters return no results on the Glossary Index page.
                <br/><i>Works only if the "Show the search on the Glossary Index page" is enabled.</i></td>
        </tr>
        <tr valign="top">
            <th scope="row">Text for "All Categories" option on the Glossary Index page</th>
            <td><input type="text" name="cmtt_glossary_AllCategoriesLabel" value="<?php echo esc_attr(\CM\CMTT_Settings::get('cmtt_glossary_AllCategoriesLabel')); ?>" /></td>
            <td colspan="2" class="cmtt_field_help_container">The label for "All Categories" selection on the Glossary Index page.</td>
        </tr>
        <tr valign="top">
            <th scope="row">Label of Category selection</th>
            <td><input type="text" name="cmtt_glossaryCategoriesLabel" value="<?php echo \CM\CMTT_Settings::get('cmtt_glossaryCategoriesLabel'); ?>"  /></td>
            <td colspan="2" class="cmtt_field_help_container">Select the label for the categories on the Glossary Index Page</td>
        </tr>
        <tr valign="top">
            <th scope="row">Label of Category selection (for dropdown)</th>
            <td><input type="text" name="cmtt_glossaryCategoriesLabelForDropdown" value="<?php echo \CM\CMTT_Settings::get('cmtt_glossaryCategoriesLabelForDropdown'); ?>"  /></td>
            <td colspan="2" class="cmtt_field_help_container">Select the label for the categories dropdown on the Glossary Index Page</td>
        </tr>
        <tr valign="top">
            <th scope="row">Label of tags</th>
            <td><input type="text" name="cmtt_glossaryTagsLabel" value="<?php echo \CM\CMTT_Settings::get('cmtt_glossaryTagsLabel'); ?>"  /></td>
            <td colspan="2" class="cmtt_field_help_container">Select the label for the tags (both on the Glossary Index and in the term page)</td>
        </tr>
        <tr valign="top">
            <th scope="row">"Showing terms with tag" label</th>
            <td><input type="text" name="cmtt_glossaryHiddenTagsLabel" value="<?php echo \CM\CMTT_Settings::get('cmtt_glossaryHiddenTagsLabel'); ?>"  /></td>
            <td colspan="2" class="cmtt_field_help_container">
            </td>
        </tr>
        <tr valign="top">
            <th scope="row">Label of the clear link on the Glossary Index page</th>
            <td><input type="text" name="cmtt_glossary_ClearLabel" value="<?php echo esc_attr(\CM\CMTT_Settings::get('cmtt_glossary_ClearLabel')); ?>" /></td>
            <td colspan="2" class="cmtt_field_help_container">This is the label for the clear link appearing on the Glossary Index page.
                <br/><i>Works only if the "Show the search button on the Glossary Index page" is enabled.</i></td>
        </tr>
        <tr valign="top">
            <th scope="row">Label of the elipsis on the Glossary Index page</th>
            <td><input type="text" name="cmtt_glossaryIndexTruncateLabel" value="<?php echo esc_attr(\CM\CMTT_Settings::get('cmtt_glossaryIndexTruncateLabel', __('(...)'))); ?>" /></td>
            <td colspan="2" class="cmtt_field_help_container">This is the label which appears after the truncated definition on the Glossary Index page.
                <br/><i>Works only if the "Limit the definition length" is enabled.</i></td>
        </tr>
        <tr valign="top">
            <th scope="row">Label of the Read More link on the Glossary Index page</th>
            <td><input type="text" name="cmtt_glossaryIndexDescReadMoreLabel" value="<?php echo esc_attr(\CM\CMTT_Settings::get('cmtt_glossaryIndexDescReadMoreLabel', __('Read More'))); ?>" /></td>
            <td colspan="2" class="cmtt_field_help_container">This is the label for the read more link appearing after the truncated definition on the Glossary Index page.
                <br/><i>Works only if the "Limit the definition length" is enabled.</i></td>
        </tr>
        <tr valign="top">
            <th scope="row">Label for [ALL] in alphabetic index</th>
            <td>
                <input type="text" name="cmtt_index_allLabel" value="<?php echo \CM\CMTT_Settings::get('cmtt_index_allLabel', 'ALL'); ?>" />
            </td>
            <td colspan="2" class="cmtt_field_help_container">Label for the option displaying all terms in the alphabetic index. Displays [ALL] by default.</td>
        </tr>
        <tr valign="top">
            <th scope="row">Prefix of the title:</th>
            <td><input  type="text" name="cmtt_glossaryBeforeTitle" value="<?php echo \CM\CMTT_Settings::get('cmtt_glossaryBeforeTitle'); ?>" /></td>
            <td colspan="2" class="cmtt_field_help_container">What text should appear before the term title on the Glossary Term page
                (e.g. if prefix is "Term:" the glossary term title would appear as "Term: Something")</td>
        </tr>
        <tr valign="top">
            <th scope="row">Back link text (top)</th>
            <td><input type="text" name="cmtt_glossary_backLinkText" value="<?php echo esc_attr(\CM\CMTT_Settings::get('cmtt_glossary_backLinkText')); ?>" /></td>
            <td colspan="2" class="cmtt_field_help_container">Text to display as backlink</td>
        </tr>
        <tr valign="top">
            <th scope="row">Back link text (bottom)</th>
            <td><input type="text" name="cmtt_glossary_backLinkBottomText" value="<?php echo esc_attr(\CM\CMTT_Settings::get('cmtt_glossary_backLinkBottomText')); ?>" /></td>
            <td colspan="2" class="cmtt_field_help_container">Text to display as backlink</td>
        </tr>
        <tr valign="top">
            <th scope="row">Title of related articles:</th>
            <td><input  type="text" name="cmtt_glossary_showRelatedArticlesTitle" value="<?php echo \CM\CMTT_Settings::get('cmtt_glossary_showRelatedArticlesTitle'); ?>" /></td>
            <td colspan="2" class="cmtt_field_help_container">What should be the title of related articles widget?</td>
        </tr>
        <tr valign="top">
            <th scope="row">Number of related glossary terms:</th>
            <td><input type="number" name="cmtt_glossary_showRelatedArticlesGlossaryCount" value="<?php echo \CM\CMTT_Settings::get('cmtt_glossary_showRelatedArticlesGlossaryCount'); ?>" /></td>
            <td colspan="2" class="cmtt_field_help_container">How many related glossary terms should be shown? Works only if "Show related articles and glossary terms together" is enabled</td>
        </tr>
        <tr valign="top">
            <th scope="row">Title of related glossary terms list:</th>
            <td><input  type="text" name="cmtt_glossary_showRelatedArticlesGlossaryTitle" value="<?php echo \CM\CMTT_Settings::get('cmtt_glossary_showRelatedArticlesGlossaryTitle'); ?>" /></td>
            <td colspan="2" class="cmtt_field_help_container">What should be the title of related glossary terms widget? Works only if "Show related articles and glossary terms together" is enabled</td>
        </tr>
        <tr valign="top">
            <th scope="row">Prefix for related articles that are glossary terms:</th>
            <td><input type="text" name="cmtt_glossary_relatedArticlesPrefix" value="<?php echo esc_attr(\CM\CMTT_Settings::get('cmtt_glossary_relatedArticlesPrefix')); ?>"/>
            </td>
            <td colspan="2" class="cmtt_field_help_container">Prefix for related articles that are glossary terms (leave empty to disable). Works only if "Show related articles and glossary terms together" is enabled</td>
        </tr>
        <tr valign="top">
            <th scope="row">Prefix for related articles that are not glossary terms:</th>
            <td><input type="text" name="cmtt_glossary_relatedArticlesPrefixNotGlossary"
                       value="<?php echo esc_attr( \CM\CMTT_Settings::get( 'cmtt_glossary_relatedArticlesPrefixNotGlossary' ) ); ?>"/>
            </td>
            <td colspan="2" class="cmtt_field_help_container">Prefix for related articles that are not glossary terms (leave
                empty to disable)
            </td>
        </tr>
        <tr valign="top">
            <th scope="row">Title of linked glossary terms list:</th>
            <td><input  type="text" name="cmtt_glossary_showRelatedTermsTitle" value="<?php echo \CM\CMTT_Settings::get('cmtt_glossary_showRelatedTermsTitle'); ?>" /></td>
            <td colspan="2" class="cmtt_field_help_container">What should be the title of linked glossary items widget?</td>
        </tr>
        <tr valign="top">
            <th scope="row">Prefix for linked glossary terms:</th>
            <td><input type="text" name="cmtt_glossary_relatedTermsPrefix" value="<?php echo esc_attr(\CM\CMTT_Settings::get('cmtt_glossary_relatedTermsPrefix')); ?>"/>
            </td>
            <td colspan="2" class="cmtt_field_help_container">Prefix for linked glossary items (leave empty to disable).</td>
        </tr>
        <tr valign="top">
            <th scope="row">Title of synonyms list:</th>
            <td><input  type="text" name="cmtt_glossary_addSynonymsTitle" value="<?php echo \CM\CMTT_Settings::get('cmtt_glossary_addSynonymsTitle'); ?>" /></td>
            <td colspan="2" class="cmtt_field_help_container">What should be the title of synonyms widget?</td>
        </tr>
        <tr valign="top">
            <th scope="row">Term details link label</th>
            <td><input type="text" name="cmtt_glossaryTermDetailsLink" value="<?php echo \CM\CMTT_Settings::get('cmtt_glossaryTermDetailsLink'); ?>"  /></td>
            <td colspan="2" class="cmtt_field_help_container">Select the label for the link to the term details which shows in the tooltip if the length is limited.<br/>
                <i>Works only if "Show Glossary Index page with definition" is enabled</i></td>
        </tr>
        <tr valign="top">
            <th scope="row">Label for the link when mobile support is on:</th>
            <td><input type="text" name="cmtt_glossaryMobileSupportLabel" value="<?php echo \CM\CMTT_Settings::get('cmtt_glossaryMobileSupportLabel'); ?>"  /></td>
            <td colspan="2" class="cmtt_field_help_container">Label for the link to Glossary Term page which appears in the tooltip when the mobile device is detected.</td>
        </tr>
        <tr valign="top">
            <th scope="row">Label for Categories on single Glossary Page:</th>
            <td><input type="text" name="cmtt_term_taxonomy_label_glossary-categories" value="<?php echo \CM\CMTT_Settings::get('cmtt_term_taxonomy_label_glossary-categories', 'Categories:'); ?>"  /></td>
            <td colspan="2" class="cmtt_field_help_container">Label for list of the Categories on the single Glossary Page.</td>
        </tr>
        <tr valign="top">
            <th scope="row">Label for Tags on single Glossary Page:</th>
            <td><input type="text" name="cmtt_term_taxonomy_label_glossary-tags" value="<?php echo \CM\CMTT_Settings::get('cmtt_term_taxonomy_label_glossary-tags', 'Tags:'); ?>"  /></td>
            <td colspan="2" class="cmtt_field_help_container">Label for list of the Tags on the single Glossary Page.</td>
        </tr>
        <tr valign="top">
            <th scope="row">Label for "Back to Top" on Glossary Index Page</th>
            <td><input type="text" name="cmtt_tooltipExpandBackToTopLabel" value="<?php echo \CM\CMTT_Settings::get('cmtt_tooltipExpandBackToTopLabel', 'Back to Top'); ?>"  /></td>
            <td colspan="2" class="cmtt_field_help_container">Label for text appearing in "Expand + Description" Index Page type</td>
        </tr>
        <tr valign="top">
            <th scope="row">Label for alternative meanings section on Glossary Term Page</th>
            <td><input type="text" name="cmtt_glossary_AlternativeMeaningLabel" value="<?php echo esc_attr(\CM\CMTT_Settings::get('cmtt_glossary_AlternativeMeaningLabel', 'Alternative Meanings:')); ?>" /></td>
            <td colspan="2" class="cmtt_field_help_container">This is the label indicating the start of the alternative meaning of the term (if term has multiple different meanings).
                <br/><i>Works only if the "Show the alternative menaings" is enabled.</i>
                <br/><i>%d - will be replaced with the number representing n-th alternative meaning (can be omitted)</i>
            </td>
        </tr>
        <tr valign="top">
            <th scope="row">Label before term title on custom template</th>
            <td><input type="text" name="cmtt_glossaryCustomTemplateBeforeTitle" value="<?php echo \CM\CMTT_Settings::get('cmtt_glossaryCustomTemplateBeforeTitle', 'Term: '); ?>" /></td>
            <td colspan="2" class="cmtt_field_help_container">
            </td>
        </tr>
        <tr valign="top">
            <th scope="row">Label for the "Embed"</th>
            <td><input type="text" name="cmtt_embed_text" value="<?php echo \CM\CMTT_Settings::get('cmtt_embed_text', 'Embed'); ?>" /></td>
            <td colspan="2" class="cmtt_field_help_container">
            </td>
        </tr>
        <tr valign="top">
            <th scope="row">Label for the "Embed Glossary Term"</th>
            <td><input type="text" name="cmtt_embed_glossary_text" value="<?php echo \CM\CMTT_Settings::get('cmtt_embed_glossary_text', 'Embed Glossary Term'); ?>" /></td>
            <td colspan="2" class="cmtt_field_help_container">
            </td>
        </tr>
        <tr valign="top">
            <th scope="row">Label for the "Copy the following HTML iframe code to your website:"</th>
            <td><input type="text" name="cmtt_embed_copy_html_text" value="<?php echo \CM\CMTT_Settings::get('cmtt_embed_copy_html_text', 'Copy the following HTML iframe code to your website:'); ?>" /></td>
            <td colspan="2" class="cmtt_field_help_container">
            </td>
        </tr>
        <tr valign="top">
            <th scope="row">Label for the "Copy to clipboard"</th>
            <td><input type="text" name="cmtt_embed_copy_clipboard_text" value="<?php echo \CM\CMTT_Settings::get('cmtt_embed_copy_clipboard_text', 'Copy to clipboard'); ?>" /></td>
            <td colspan="2" class="cmtt_field_help_container">
            </td>
        </tr>
        <tr valign="top">
            <th scope="row">Label for the "Term" in Term + Definition display style</th>
            <td>
                <input type="text"
                       name="cmtt_term_defition_term_label"
                       value="<?php echo \CM\CMTT_Settings::get('cmtt_term_defition_term_label', 'Term'); ?>" />
            </td>
            <td colspan="2" class="cmtt_field_help_container">
                Leave empty to remove header row
            </td>
        </tr>
        <tr valign="top">
            <th scope="row">Label for the "Definition" in Term + Definition display style</th>
            <td>
                <input type="text"
                       name="cmtt_term_defition_definition_label"
                       value="<?php echo \CM\CMTT_Settings::get('cmtt_term_defition_definition_label', 'Definition'); ?>" />
            </td>
            <td colspan="2" class="cmtt_field_help_container">
                Leave empty to remove header row
            </td>
        </tr>
        <tr valign="top">
            <th scope="row">Label for the "Full Description" in "Word of the day/week" widget</th>
            <td>
                <input type="text"
                       name="cmtt_word_of_the_day_fulldesc_label"
                       value="<?php echo \CM\CMTT_Settings::get('cmtt_word_of_the_day_fulldesc_label', 'Full Description'); ?>" />
            </td>
        </tr>
        <tr valign="top">
            <th scope="row">Label for the "Glossary" in "Word of the day/week" widget</th>
            <td>
                <input type="text"
                       name="cmtt_word_of_the_day_glossary_label"
                       value="<?php echo \CM\CMTT_Settings::get('cmtt_word_of_the_day_glossary_label', 'Glossary'); ?>" />
            </td>
        </tr>
        <?php do_action('cmtt_settings_labels_content_end'); ?>
    </table>
</div>